Navigation
MateuszPiaszczyk/MoviesBrowser pull request #16
Opened 2023-05-12 14:21 UTC by MateuszPiaszczyk

Navigation corrected :)

2023-05-12 16:11 UTC, BoAneta requested changes
There are few small things that needs to be change. But rest look good :)

2023-05-12 16:11 UTC, BoAneta commented on src/common/Navigation/styled.js
I think changes are good :) but there are still some mistakes:
Line 67 and 70 in styled Icon should be width: not weight:,
Line 77 and 78 are missing ; at the end
also line 78 and 79 are missing space afer :

2023-05-12 16:11 UTC, BoAneta commented on src/index.js
this is old view of our core index.js, please update from the main branch.

The rest look great :) few small things and we can marge.

2023-05-12 16:18 UTC, MateuszPiaszczyk commented on src/common/Navigation/styled.js
thank you for the tips :) I'm correcting :)

2023-05-14 14:56 UTC, MateuszPiaszczyk reviewed
changes are made in App.js routers.js and main index. js. So index.js from App folder can be removed now :)

2023-05-14 18:00 UTC, Dawid-Zieba approved these changes
Cosmetic changes looks clean, now navigation should run with no problems.

2023-05-14 18:05 UTC, merged